### Challenge Test 4

##### 1. Escribe una función suma_columnas(v) que dado un ndarray de tamaño n x m devuelva un ndarray de tamaño m con la suma de sus columnas

In [6]:
import numpy as np


def suma_columnas(v):
    
    g = np.zeros(v.shape[1], "int64")

    for i in range(v.shape[0]):
        
        g += v[i]
    
    return g

#O

def suma_columnas2(v):
    return np.sum(v, axis=0)

a=np.array([[124,2,3],[4,5,6]])

print(suma_columnas(a))
print(suma_columnas2(a))

[128   7   9]
[128   7   9]


##### Apuntes:

En NumPy, no es recomendable inicializar un ndarray como un array vacío cuando planeas agregar elementos a él en un bucle, especialmente si el tamaño final del array es conocido de antemano. Esto se debe a que la adición de elementos a un array en un bucle no es eficiente y puede llevar a errores si no se hace correctamente. En este caso es mejor inicializarlo con ceros.


##### 2. Escribe una función filtro(v, x) que dado un ndarray v y un número x, devuelva un ndarray con los valores de v que sean mayores que x

In [2]:
def filtro(v,x):
    
    return v[v>x]

a=np.array([[124,2,3],[4,5,6]])
filtro(a, 3)

array([124,   4,   5,   6])

##### 3. Calcula la mediana, la moda y la desviación estándar de un conjunto de datos representado como un ndarray

In [32]:
import numpy as np
from scipy.stats import mode

a = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])

mediana = np.median(a)
moda = mode(a.flatten())[0][0]
desviacion_estandar = np.std(a)

print(f"La mediana es {mediana}, la moda es {moda} y la desviación estándar es {desviacion_estandar}")

La mediana es 5.0, la moda es 5 y la desviación estándar es 1.8856180831641267


##### Apuntes:
Para usar la moda debe importarse la función mode del paquete scipy.stats, y utilizar la función np.flatten() para que recoja un vector unidimensional. mode() proporciona dos valores, la moda y el número de veces que se ha contado dicha moda, por ello cogemos el primer elemento mode()[0].

##### 4. Dado un ndarray v de dimensiones n x m y valor x, calcula un ndarray con los valores -1, 0, 1 en cada posición i,j dependiendo de si el valor v[i,j] es, respectivamente, menor, igual o mayor que el valor de v[x,j]
Por ejemplo:
con x = 2

v:

[[0.46073859 0.63000055 0.4527522 ]

[0.90487794 0.81662706 0.08923395]

[0.11465189 0.76878634 0.41317721]

[0.84451333 0.51610403 0.4688711 ]]

Resultado:

[[ 1 -1 1]

[ 1 1 -1]

[ 0 0 0]

[ 1 -1 1]]

In [4]:
def arraymod(v, x):
    
    n, m = v.shape
    a = np.zeros((n, m), dtype = int)
    
    for j in range(m):
        valor_referencia = v[x, j]
        for i in range(n):
            if v[i, j] < valor_referencia:
                a[i, j] = -1
            elif v[i, j] > valor_referencia:
                a[i, j] = 1
            #else:
            #a[i,j] = 0 pero no hace falta ya que he inicializado el vector con 0s
    return a



b = np.array([[0.46073859,0.63000055,0.4527522],
[0.90487794,0.81662706,0.08923395],
[0.11465189,0.76878634,0.41317721],
[0.84451333,0.51610403,0.4688711]])

arraymod(b, 2)

array([[ 1, -1,  1],
       [ 1,  1, -1],
       [ 0,  0,  0],
       [ 1, -1,  1]])

##### 5. La criba de Eratóstenes permite determinar los número primeros menores que un determinado valor. El procedimiento a seguir es:

-Generar los valores entre 1 y N. En nuestro caso, por ejemplo, 10 millones

-Eliminar los valores de 2 en 2, luego de 3 en 3, y así sucesivamente. Mientras sea posible.

Los que queden serán los números primeros menores que N

Implementa una función que realice la criba y pruébalo con N= 10 millones

In [5]:
#Opción 1 (Enfoque poco eficaz pero intuitivo)

def criba_eratostenes(n):
    
    numeros = np.arange(0, n + 1)
    mascara = np.ones(n+1, dtype=bool)
    mascara[0:2] = 0  #0 y 1 no son primos
    
    # Empezar desde el primer número primo, que es 2
    for i in range(2, int(n)+1):
        if mascara[i] == 1:
            # 2*i porque queremos que i se quede como 1
            mascara[2*i:n+1:i] = 0
    
    return numeros[mascara]

#Opción 2 (Enfoque eficaz)

def criba_eratostenes2(n):
    #n+1 para que los indices coincidan con los números
    primos = np.ones(n+1, dtype=bool)
    primos[0:2] = 0 # 0 y 1 no son primos
    
    #vale la gracia de esto es que todos los números compuestos en n 
    #deben tener al menos un factor menor o igual a la raíz cuadrada de n
    
    for i in range(2, int(np.sqrt(n)) + 1):#range(i,j) va de i a j-1, por eso el +1
        if primos[i]==1:
            #Comenzamos a marcar desde i*i porque cualquier múltiplo menor de i 
            #ya habrá sido marcado por números primos menores que i
            primos[i*i:n+1:i] = 0
            
    return np.nonzero(primos)[0]#el primer elemento es el array en sí

a = 10000000
primos = criba_eratostenes(a)

print(f"Se encontraron {len(primos)} números primos menores que {a}")
print("Algunos de los números primos encontrados:", primos[:10])  

Se encontraron 664579 números primos menores que 10000000
Algunos de los números primos encontrados: [ 2  3  5  7 11 13 17 19 23 29]


##### 6. Escribe un script que compare la eficiencia de usar vectorización respecto a aplicar directamente la función a cada elemento. Para ello genera una matriz aleatoria suficientemente grande. Programa una función que, para un valor v[i,j] calcule la media de los valores que tiene a la izquierda, a la derecha, arriba y abajo (aquellos que existan)

In [6]:
from numpy import random
import timeit
def mediavecinos(matriz, i, j):
    
    suma = 0
    count = 0
    
    # Vecino izquierdo
    if j > 0:
        suma += matriz[i, j-1]
        count += 1
    # Vecino derecho
    if j < matriz.shape[1] - 1:
        suma += matriz[i, j+1]
        count += 1
    # Vecino superior
    if i > 0:
        suma += matriz[i-1, j]
        count += 1
    # Vecino inferior
    if i < matriz.shape[0] - 1:
        suma += matriz[i+1, j]
        count += 1
    
    # Calcular la media si hay vecinos válidos
    if count > 0:
        return suma / count
    else:
        return 0
    
n = 1000
m = 1000
matriz = random.rand(n,m)
matriz

def calcular_media_elemento(matriz):
    resultado = np.zeros(matriz.shape, dtype=float)
    for i in range(matriz.shape[0]):
        for j in range(matriz.shape[1]):
            resultado[i, j] = mediavecinos(matriz, i, j)
    return resultado

print(calcular_media_elemento(matriz))

def calcular_media_vectorizada(matriz):
    
    resultado = np.zeros(matriz.shape, dtype=float)
    
    # Sumar los vecinos izquierdos (si existen)
    resultado[:, :-1] += matriz[:, 1:]
    
    # Sumar los vecinos derechos (si existen)
    resultado[:, 1:] += matriz[:, :-1]
    
    # Sumar los vecinos superiores (si existen)
    resultado[:-1, :] += matriz[1:, :]
    
    # Sumar los vecinos inferiores (si existen)
    resultado[1:, :] += matriz[:-1, :]
    
     # Ajustar divisiones para bordes y esquinas
    # Esquina superior izquierda
    resultado[0, 0] /= 2
    
    # Esquina superior derecha
    resultado[0, -1] /= 2
    
    # Esquina inferior izquierda
    resultado[-1, 0] /= 2
    
    # Esquina inferior derecha
    resultado[-1, -1] /= 2
    
    # Borde superior (excluyendo esquinas)
    resultado[0, 1:-1] /= 3
    
    # Borde inferior (excluyendo esquinas)
    resultado[-1, 1:-1] /= 3
    
    # Borde izquierdo (excluyendo esquinas)
    resultado[1:-1, 0] /= 3
    
    # Borde derecho (excluyendo esquinas)
    resultado[1:-1, -1] /= 3
    
    # Dividir por 4 para obtener la media para los elementos internos
    resultado[1:-1, 1:-1] /= 4
    
    return resultado

print(calcular_media_vectorizada(matriz))

print("Tiempo usando bucle sobre elementos:")
time_elemento = timeit.timeit(lambda: calcular_media_elemento(matriz), number=1)
print(f"Tiempo: {time_elemento:.4f} segundos")

print("\nTiempo usando vectorización:")
time_vectorizado = timeit.timeit(lambda: calcular_media_vectorizada(matriz), number=1)
print(f"Tiempo: {time_vectorizado:.4f} segundos")

[[0.45923616 0.7160506  0.61784643 ... 0.62399572 0.74395383 0.10318657]
 [0.76717082 0.70638916 0.65720836 ... 0.61381949 0.3628495  0.91293889]
 [0.76296927 0.73621977 0.62439735 ... 0.48680554 0.82479703 0.32589507]
 ...
 [0.50798458 0.32022996 0.43348298 ... 0.34444737 0.14417502 0.27234716]
 [0.44334156 0.5294749  0.64724514 ... 0.23784238 0.20013425 0.22026183]
 [0.74146567 0.62733008 0.53944943 ... 0.1709031  0.40267883 0.05697438]]
[[0.45923616 0.7160506  0.61784643 ... 0.62399572 0.74395383 0.10318657]
 [0.76717082 0.70638916 0.65720836 ... 0.61381949 0.3628495  0.91293889]
 [0.76296927 0.73621977 0.62439735 ... 0.48680554 0.82479703 0.32589507]
 ...
 [0.50798458 0.32022996 0.43348298 ... 0.34444737 0.14417502 0.27234716]
 [0.44334156 0.5294749  0.64724514 ... 0.23784238 0.20013425 0.22026183]
 [0.74146567 0.62733008 0.53944943 ... 0.1709031  0.40267883 0.05697438]]
Tiempo usando bucle sobre elementos:
Tiempo: 3.5412 segundos

Tiempo usando vectorización:
Tiempo: 0.0263 segund

##### 7. Usando scipy.optimize.fsolve escribe el código para resolver el sistema de ecuaciones:

    x**2 + y**2 = 10

    x * math.exp(y) = 1

In [7]:
from scipy.optimize import fsolve
from math import exp

def nonlin(v):
    x,y = v
    return[x**2 + y**2 -10,
          x * exp(y) - 1]
root = fsolve(nonlin,[1,1])

print(root)
print(nonlin(root))

[ 2.96912066 -1.08826583]
[-9.112710586123285e-13, -3.571032358706816e-12]
